### ISSUE TITLE
Değişkene atanan bütün/tam sayı değerleri çıktı değerleri ile bir olsun

### ISSUE THREAD

**Issue by datadeveb** [erhanbaris/karamel#14]
s.a. kolay gelsin.

Değişkene atadığımız herhangi bir bütün/tam sayı atadığımız gibi çıktıda yansıtılsa. 2021 sayısı kullanıyorum çıktıda 2021.0 sayısı veriyor. Bu benim istediğim bir durum değil. Verdiğim sayı verdiğim gibi çıkar ise daha iyi olur.

Örneğin bir değişkene yıl amacı ile 2021 yazıyorum ve söz içinde geçerken 2021.0 olarak karşıma çıkıyor. Yazı etkisinde girsem bir altında matematik işleminde kullanacağım zaman başka bir uğraş gerekiyor.

Teşekkürler.

**Comment by erhanbaris** [comment]
Karamel dili içerisinde tam sayı ve kesirli sayılar, kesirli sayı formatında tutuluyor. Bu şekilde yapılması performansı arttırıyor.
Sayıların yazıya çevirinde kontrol eklenerek sayı kesirli değil ise tam sayıya çevrilip yazıya dönüştürülmesi sağlandı.
