### ISSUE TITLE
Türkçe Yazılım Konatı'ndan

### ISSUE THREAD

**Issue by datadeveb** [erhanbaris/karamel#22]
Aşağıdaki bağlantı örkleri "Türkçe Yazılım Konatı" altında gündeme getirilen konulara yönlendiren bağlantı örkleridir.

**Comment by datadeveb** [comment]
https://github.com/turkce-yazilim-konati/karamel/issues/4

**Comment by erhanbaris** [comment]
Sorun düzeltildi. Online test kısmında deneyebilirsiniz.
