### ISSUE TITLE
Opcode sayısının azaltılması gerekiyor

### ISSUE THREAD

**Issue by erhanbaris** [erhanbaris/karamel#27]
<= ve >= 
<   ve >
aslında aynı işlemler. Tek fark parametrelerin yerinin değişmesi.
Aynı zamanda
InitArguments
InitList
InitDict tek Opcode altında toplanması gerekiyor.

**Comment by volkantash** [comment]
Birini kaldırmayı mı amaçlıyorsun?

**Comment by erhanbaris** [comment]
Fazladan olanları kaldırıcam. Örneğin:
- InitArguments
- InitList
- InitDict
yerine Init isminde bir OpCode tanımlayıp tip parametresi ile işlemler yapılacak.

Büyüktür küçüktür işaretleri için ise a > b ifadesi ile b < a ifadesi aynı sonucu verir. Fazladan OpCode gerek yok. Tek OpCode ile aynı sonuç alınabilir ve aynı zamanda da performans artışı sağlanır.

**Comment by volkantash** [comment]
Yazılımcıya sunulan esnek yazış özelliğinden ıraklaşmak başarı sağlayacak mı?

**Comment by erhanbaris** [comment]
Bunu hiçbir yazılımcı görmüyor ve kullanamaz. Bu tamamen dilin en düşük seviyede işlemleri.

**Comment by erhanbaris** [comment]
Düzenlemeler ile eskisine göre %7 daha performanslı çalışıyor.
