### ISSUE TITLE
Yazım Yanlışı Var

### ISSUE THREAD

**Issue by datadeveb** [erhanbaris/karamel#4]
https://erhanbaris.github.io/karamel/karamelweb/src/www/

Bir iki yazım yanlışı gördüm. Düzeltilmeli. 
| Yanlış | Doğru |
| ------ | ------ | 
| // İyi değişkeni topla | // İki değişkeni topla |
| faktoriyel | faktöriyel |

Öte yandan ayrı yazılması gereken sözcüklere bir yöntem geliştirmeliyiz. Aşağıdakiler ilk akla gelen örnekler.
ya-da, ya\~da, ya.da, ya_da
devam-et, devam\~et, devam.et, devam_et

**Comment by erhanbaris** [comment]
Yazim hatalari duzeltildi. 'devamet' sozcugu 'devam' ile, 'yada' sozcugu 'yoksa' olarak degistirildi.
'yoksa' sozcugu icin farkli bir oneri olursa bu bilet tekrardan acilabilir.
