### ISSUE TITLE
Ayrı yazılması gereken sözcükleri yazılım dilinde kullanma

### ISSUE THREAD

**Issue by datadeveb** [erhanbaris/karamel#5]
Programlama yaparken "devam et" gibi iki sözcükten oluşan eylemleri "devamet" biçiminde yazmak dil alışkanlığımızı bozacaktır. Bu alışkanlık yazılımcılardan halka ve sonrasında dile sıçrayabilir. Bu nedenle bunun ayrı olduğu bir biçimde anlaşılır kılınmalıdır. Kılığı aşağıdakiler gibi olabilir

devam_et
devam\~et
devam-et
devam.et

**Comment by erhanbaris** [comment]
'devamet' sozcugu 'devam' olarak degistirildi. Olabildigince tek kelimeden olusan yapilar kurgulamaya calismamiz lazim.
