### ISSUE TITLE
Yeni sözdizimi isteği

### ISSUE THREAD

**Issue by Denizhan1103** [erhanbaris/karamel#6]
Merhaba . Eğer mümkünse ekstra olarak bracket syntax eklenmesini istiyorum .

**Comment by datadeveb** [comment]
Daha açık yazabilir misiniz? Ne tür bir istek bu.

**Comment by datadeveb** [comment]
> 
> 
> Merhaba . Eğer mümkünse ekstra olarak bracket syntax eklenmesini istiyorum .

Daha açık yazabilir misiniz? Ne tür bir istek bu?

**Comment by datadeveb** [comment]
> 
> 
> Merhaba . Eğer mümkünse ekstra olarak bracket syntax eklenmesini istiyorum .

Merhaba. Daha açık yazabilir misiniz? Ne tür bir istek bu?

**Comment by erhanbaris** [comment]
Tam olarak ne istendiğini anlamadım.
liste yada sözlük nesnelerine erişimde listem[0] gibi bir kullanım mı olmasını istiyorsun yoksa 
eğer a == b ise {
}
şeklinde bir kullanım mı olmasını istiyorsun?

**Comment by erhanbaris** [comment]
Cevap gelmedigi icin bileti kapatiyorum
