### ISSUE TITLE
küçükharf(), büyükharf()

### ISSUE THREAD

**Issue by datadeveb** [erhanbaris/karamel#7]
selamun aleykum. 

küçükharf() yerine harfküçült() / harfiküçült()
büyükharf() yerine harfbüyült() / harfibüyült()

öneriyorum. 

Çünkü küçükharf yazınca veriyi küçükharf olarak tanı olarak anlaşılıyor. Sözcüğün dokunduğu bir anlam daha var. Boyut olarak küçük büyük durumu. Bunun için de harfboyuküçült(), harfboyubüyült() gibi gerektiğinde oluşturulabilir.

**Comment by erhanbaris** [comment]
harfleriküçült() ve harfleribüyült() daha uygun görünüyor.
Yazı içerisinden birden fazla harf olabileceği için çoğul kullanmak daha mantıklı.

**Comment by erhanbaris** [comment]
harfleriküçült() ve harfleribüyült() olarak değiştirildi.

**Comment by datadeveb** [comment]
Konuyu dilbilimci ve bu alanla ilgilenen kişilere yönlendiriyorum. Hangisinin hangi açıdan ne olacağını bir de onlardan dinleyelim.

**Comment by fdemir** [comment]
sözbüyült() ve sözküçült() daha iyi olmaz mı? harfleribüyült uzun ve okunabilirliği azaltıyor.

**Comment by erhanbaris** [comment]
@fdemir sözbüyült ve sözküçült tam olarak fonksiyonun amacını yansıtmıyor. Burada değiştirilen harfler olduğu için özellikle harfleriküçült olmasını seçtim. Diğer bir açıdan haklısın, biraz uzun oldu. Daha kısa olması okunaklılığı arttırır.
İngilizcede ki karşılıkları şöyle:
- tolower()
- tolowercase()
- lowercase()
Bu sözcükler üzerinden gidilir ise daha faydalı olur diye düşünüyorum

@datadeveb konuyu başka alanlarda tartışmayalım, konuyu buradan tartışalım. O tartışmada iki saat önce açılmış, çok dallanma budaklanma olmasın bence.

**Comment by datadeveb** [comment]
> 
> @datadeveb konuyu başka alanlarda tartışmayalım, konuyu buradan tartışalım. O tartışmada iki saat önce açılmış, çok dallanma budaklanma olmasın bence.

İlgili tartışmalara birbirine erişebilecek biçimde örk (link) ekliyoruz. Burada olan ilgili bir konu "yazılımca" altına eklenmez ise olmaz. Sağlıklı bir iletişim ağı önemli. https://github.com/turkce-yazilim-konati/yazilimca/discussions

**Comment by datadeveb** [comment]
https://github.com/turkce-yazilim-konati/yazilimca/discussions/32#discussioncomment-568747

**Comment by erhanbaris** [comment]
harfleriküçült ve harfleribüyült su an icin en iyi secenek olarak gorunuyor. Daha uygun bir isim bulunamadigi icin bileti kapatiyorum.
