### ISSUE TITLE
Türkçeye daha uygun bir sözdizim önerisi

### ISSUE THREAD

**Issue by datadeveb** [erhanbaris/karamel#8]
https://github.com/turkce-yazilim-konati/yazilimca/discussions/34#discussioncomment-570022
Ekrana yazı basacağımız zaman Türkçe dil yapısına uygun biçimde şöyle yazabiliriz.

```
şunu_bas("Ekrana basılacak yazı")
```

**Okuyuş amaçlı bir örnek**
```
x < 5 ise:
    şunu_bas("Ekrana basılacak yazı")
```

Bakınız şöyle yazdığımızda yanlış kurulmuş söz gibi geliyor insana. Bu nedenle üstteki daha doğrudur.
```
x < 5 ise:
    bas("Ekrana basılacak yazı")
```

Hakksız mıyım?

**Comment by erhanbaris** [comment]
Bunu daha kisaltmakta mumkun.
```
x < 5:
    bas("Ekrana basılacak yazı")
```
Bence bu sekilde olmasi daha uygun, nedeni de daha az komut yazilmasi.

**Comment by datadeveb** [comment]
> 
> 
> Bunu daha kisaltmakta mumkun.
> 
> ```
> x < 5:
>     bas("Ekrana basılacak yazı")
> ```
> 
> Bence bu sekilde olmasi daha uygun, nedeni de daha az komut yazilmasi.

Kısaltılmamalı. Neden? Bunu bir söz örneği kurarak anlatmaya çalışacağım.

Oktay, bugün iş toplantılarımız sıkıntılı geçti. Selma Hanıma bilgi göndermelisin. Şunu yaz: "Selma Hanım, Hemen görüşmeliyiz! Toplantılar sıkıntılı geçti. Geçecek gibi de görünüyor."

Şimdi sözümüzü şöyle kuralım.
Oktay, bugün iş toplantılarımız sıkıntılı geçti. Selma Hanıma bilgi göndermelisin. Yaz: "Selma Hanım, Hemen görüşmeliyiz! Toplantılar sıkıntılı geçti. Geçecek gibi de görünüyor."

İşte yukarıdaki önerimde şunu_bas gibi bir kullanım bu nedenle gereklidir. Öte yandan bu bir de şöyle bir kolaylık sağlıyor. Bu tür komutlar hep "şunu_" ile başlayacağı için yazılımlarımızı yazar iken bir dizme içinde seçimi düzenli olabilir.

şunu_bas()
şunu_yaz()
şunu_topla()
şunu_ayıkla()
şunu_dağıt()
şunu_sil()
şunu_büyült()
...

**Comment by erhanbaris** [comment]
sunu_bas sunu_yaz gibi fonksiyon isimleri gelistiricinin elinde olan birsey. Benim odaklandigim nokta burada eger ifadesinin (if condition) daha pratik ve kisa hale getirilmesi. 
Kelimenin bastan sona alinmasindan ise tamamen kaldirilmasi bence daha mantikli. Daha az kod yazarak ayni sonucu elde etmek var iken neden fazladan kod yazmak isteyeyim ki?
Misal 

```
eger 10 buyuktur 5 ise:
     gc::satiryaz('10 buyuktur 5')
```
yerine
```
10 > 5: 
     gc::satiryaz('10 buyuktur 5')
```

Yazmayi tercih ederim.

**Comment by datadeveb** [comment]
Türkçe tabanlı bir düzende yapabildiğimiz en kısa ve doğru düşünceyi sağlayan düzen yeğlenir. Sıkıntı yok. Önemli olan kodları okurken Türkçe söz okurcasına bir durumu sunabilmek. 

Okuyuşları ele alalım.

Eğer on büyüktür beş ise satıryaz on büyüktür beş.
On büyüktür beş satıryaz on büyüktür beş. 
On büyüktür beş ise satıryaz on büyüktür beş.
Eğer on büyüktür beş satıryaz on büyüktür beş.
On büyüktür beş ise şunu yaz on büyüktür beş.

Diye giden söz dizimlerimiz söz konusu oluyor. Burada daha sonradan gelecek olan durumları da önümüze koymamız gerekecek.

**Comment by erhanbaris** [comment]
Yeni eğer sorgusu aşağıda ki gibi olacak.
Türkçe okuması daha kolay olduğunu düşünüyorum.

```a = 1
b = 2
c = 1

a == b ise:
    gç::satıryaz('a eşittir b')
veya a == c ise:  
    gç::satıryaz('a eşittir c')
veya:
    gç::satıryaz('a hiçbirine eşit değil')```

**Comment by erhanbaris** [comment]
https://github.com/erhanbaris/karamel/commit/9a49e3b59d813d6897a4657a57424531102ba1eb
ile istek tamamlandı.

**Comment by datadeveb** [comment]
> 
> 
> Yeni eğer sorgusu aşağıda ki gibi olacak.
> Türkçe okuması daha kolay olduğunu düşünüyorum.
> 
> ```
> a = 1
> b = 2
> c = 1
> 
> a == b ise:
>     gç::satıryaz('a eşittir b')
> veya a == c ise:  
>     gç::satıryaz('a eşittir c')
> veya:
>     gç::satıryaz('a hiçbirine eşit değil')
> ```

veya bağlacının kullanılmasındaki düşünceyi anlayamadım. Aşağıdaki daha doğru olmaz mı?

``` 
a = 1
b = 2
c = 1
a==b ise:  
   gç::satıryaz('a eşittir b')
a==c ise:  
   gç::satıryaz('a eşittir c')
değilse:  
   gç::satıryaz('a hiçbirine eşit değil')
```

**Comment by erhanbaris** [comment]
> > Yeni eğer sorgusu aşağıda ki gibi olacak.
> > Türkçe okuması daha kolay olduğunu düşünüyorum.
> > ```
> > a = 1
> > b = 2
> > c = 1
> > 
> > a == b ise:
> >     gç::satıryaz('a eşittir b')
> > veya a == c ise:  
> >     gç::satıryaz('a eşittir c')
> > veya:
> >     gç::satıryaz('a hiçbirine eşit değil')
> > ```
> 
> veya bağlacının kullanılmasındaki düşünceyi anlayamadım. Aşağıdaki daha doğru olmaz mı?
> 
> ```
> a = 1
> b = 2
> c = 1
> a==b ise:  
>    gç::satıryaz('a eşittir b')
> a==c ise:  
>    gç::satıryaz('a eşittir c')
> değilse:  
>    gç::satıryaz('a hiçbirine eşit değil')
> ```

Ne yazik ki o kullanim hatali. Iki farkli sorgu cumlesi var gibi oluyor. Verdigin ornekte kucuk bir duzenleme yaptim.
```
a = 1
b = 1
c = 1
a==b ise:  
   gç::satıryaz('a eşittir b')
a==c ise:  
   gç::satıryaz('a eşittir c')
veya:  
   gç::satıryaz('a hiçbirine eşit değil')
```

Bu kodun ciktisi soyle oluyor
```
Derleme işlemi başarılı

a eşittir b
a eşittir c
```

Ama burada amaclanan ilk kosul dogru degilse ise ikinci kosulun calistirilmasi. Ama senin onerinde ki yaklasimda once ilk kosul calistiriliyor. Dogru yada yanlis olmasina bakilmaksizin ikinci kosul calistiriliyor. Bu da hatali bir durum olusturuyor.
Orada ilk kosulun hatali olmasi durumda ona bagli obur kosullarin calistirilmasi gerekiyor ve bunu bir sekilde ayristirmak gerekli. Bunun icinde veya eki kullandim.
Python da ki if else elif mantiginda ki *elif* bizde *veya* oluyor.

**Comment by datadeveb** [comment]
Evet verdiğim örnek anlattığınız gibi çıktı elde etmeye neden oluyor. Ancak sorun yine var. Anlatmaya çalışayım.

"veya" bağlacı kullanınca da program çalışma sırasında 3 olasılıktan birini çalıştıracak gibi düşündürtüyor. İşleyiş açışından böyle olmasa da. Şunun gibi bir kullanım daha anlamlı olabilir.
```
a = 1
b = 1
c = 1
a==b ise:  
   gç::satıryaz('a eşittir b')
yok a==c ise:  
   gç::satıryaz('a eşittir c')
değilse:  
   gç::satıryaz('a hiçbirine eşit değil')
```

Ya da

```
a = 1
b = 1
c = 1
a==b ise:  
   gç::satıryaz('a eşittir b')
değili a==c ise:  
   gç::satıryaz('a eşittir c')
değilse:  
   gç::satıryaz('a hiçbirine eşit değil')
```

**Comment by erhanbaris** [comment]
Bu bir sorun degil bu bir oneri. Ben sorun goremiyorum.

**Comment by datadeveb** [comment]
```
a = 1
b = 1
c = 1

a == b ise:
    gç::satıryaz('a eşittir b')
veya a == c ise:  
    gç::satıryaz('a eşittir c')
veya:
    gç::satıryaz('a hiçbirine eşit değil') 
```

veya ile yazdığımızda yazılım en az iki olasılıktan hangisini canı isterse işleme koyacak gibi anlaşılıyor.

Aşağıdakilerden yalnızca 1 tanesini çıktı alacakmışız beklentisine giriyorum.
a eşittir b
a eşittir c
a hiçbirine eşit değil

(Bu anlattığım durumu elde etmek için nasıl bir kod öbeği yazmamız gerekir?)

**Comment by erhanbaris** [comment]
a = 1
b = 1
c = 1

a == b ise:
    gç::satıryaz('a eşittir b')
veya a == c ise:  
    gç::satıryaz('a eşittir c')
veya:
    gç::satıryaz('a hiçbirine eşit değil') 

zaten sadece bir tane cikti vermesi gerekiyor.

- a eşittir b
- a eşittir c
- a hiçbirine eşit değil

Bu uc secenekten birini cikti olarak verecek.
Bu arada cani isterse cevap vermez. Yukaridan asagiya dogru tek tek sorgulari calistirir, ilk eslesen sorgunun icinde ki kod calistirilir diger kodlar atlanir.

Tam olarak ne kodu sordugunu anlamadim.

**Comment by erhanbaris** [comment]
```
var a = 1;
var b = 1;
var c = 1;

if (a == b)  
    console.log('a eşittir b');
else if (a == b)  
    console.log('a eşittir c');
else 
    console.log('a hiçbirine eşit değil');
```

Bu ustte ki kod javascript ile yazildi ve benim tasarimima oldukca benziyor ve eminim ki bu soz dizimi icin kimsenin sonuclar cani isterse cikacakmis gibi gorunmuyor demiyordur.

**Comment by datadeveb** [comment]
Orada bir karaltı var:
    Git bak bakalım:
          Araba ise:
               3 kez ışıkları yak-söndür
          veya bisiklet ise:
                2 kez ışıkları yak-söndür
          veya motor ise:
                4 kez ışıkları yak-söndür
          veya:
                1 kez ışıkları yak-söndür
                
                
Açıklama:
Gittiği yerde araba ve bisiklet bulunuyorsa ben 2 kez ya da 3 kez ışıkları yakıp söndürürüm. Şimdi burada yanıtı alan kişi öbür olasılıkların var olup olduğunu anlayamaz. Olabilir de, olmayabilir de. Ancak hangi sorgulamaya göre tepki verdiğimi belirttiğim için bisiklet olduğunu anlar.
